# 0322 TA

In [ ]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np

### 小複習

In [1]:
# 炎龍幣換台幣
def yenl2twd(yenl):
    c = 87
    twd = yenl * c
    print((f"{yenl}炎龍幣合{int(twd)}台幣"))

In [2]:
yenl2twd(10)

10炎龍幣合870台幣


In [3]:
def yenl2twd(yenl, c=87):
    twd = yenl * c
    print((f"{yenl}炎龍幣合{int(twd)}台幣"))

In [4]:
yenl2twd(10)

10炎龍幣合870台幣


In [5]:
yenl2twd(10, c=9487)

10炎龍幣合94870台幣


### list 與 array的比較

In [5]:
abc =  list(range(0,10))

In [6]:
abc

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
K = np.arange(0, 10, 1)

In [8]:
K

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
abc*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
K*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Numpy的計算功能

In [11]:
K.mean()

4.5

In [12]:
np.mean(K)

4.5

In [14]:
np.median(K)

4.5

In [15]:
K.std()

2.8722813232690143

In [16]:
K.min()

0

In [17]:
K.max()

9

In [18]:
K.sum()

45

In [19]:
K.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [20]:
K.prod()

0

In [21]:
K.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
L = np.arange(1,10,1)

In [23]:
L.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [24]:
N = L.reshape(3,3)

In [25]:
N

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
N.mean()

5.0

In [27]:
N.mean(axis = 0)

array([4., 5., 6.])

In [28]:
N.mean(axis = 1)

array([2., 5., 8.])

### Numpy random的各種形式

In [29]:
np.random.seed(1)

In [30]:
np.random.randint(10)

5

In [31]:
np.random.seed(1)

In [32]:
np.random.randint(10)

5

In [33]:
num = 0
while (num <5):
    np.random.seed(1)
    print(np.random.randint(10))
    num +=1

5
5
5
5
5


In [34]:
num = 0
np.random.seed(1)
while (num <5):
    print(np.random.randint(10))
    num +=1

5
8
9
5
0


In [35]:
np.random.randn()

-1.1059350760083153

In [36]:
num = 0
while(num < 5):
    a = np.random.randn(100,100)
    print(a.mean())
    num += 1

0.019982249882589644
0.005953584086650478
-0.020380883418141035
0.015681118103224444
-0.0087215642579591


In [37]:
num = 0
while(num < 5):
    a = np.random.randn(100,100)
    print(a.std())
    num += 1

0.9973673426538869
0.990304232834449
1.0058804319044545
0.9939668551982809
1.0041861687365312


In [38]:
S = ["apple", "orange", "banana", "guava", "grape"]

In [39]:
np.random.choice(S)

'apple'

In [40]:
np.random.choice(S,3)

array(['orange', 'guava', 'orange'], dtype='<U6')

In [41]:
np.random.choice(S, 5)

array(['grape', 'apple', 'grape', 'grape', 'banana'], dtype='<U6')

In [42]:
np.random.choice(S, 5, replace=False)

array(['guava', 'orange', 'banana', 'grape', 'apple'], dtype='<U6')

In [43]:
np.random.choice(S, size=(3,3))

array([['grape', 'guava', 'apple'],
       ['apple', 'apple', 'banana'],
       ['grape', 'grape', 'orange']], dtype='<U6')

In [44]:
P = [0.8, 0.2, 0, 0, 0]

In [45]:
np.random.choice(S, 5, p = P)

array(['apple', 'apple', 'apple', 'apple', 'apple'], dtype='<U6')